package com.droid.droidcalc.data.db

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.math.BigDecimal

/**
 * Represents a single calculation history entry in the Room database.
 * Each entry includes the expression, the result, and a timestamp.
 * The `id` is auto-generated by Room.
 *
 * @property id The unique identifier for the history entry (auto-generated).
 * @property expression The mathematical expression that was calculated (e.g., "2+2*3").
 * @property result The numerical result of the expression.
 * @property timestamp The time at which the calculation was performed, in milliseconds since epoch.
 * @author DroidSwap
 */
@Entity(tableName = "calculation_history")
data class HistoryEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val expression: String,
    val result: String, // Storing BigDecimal as String to maintain precision and avoid Room type converter complexity for now
    val timestamp: Long
)
